//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace FullContact__
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ZipPostalCodeDbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ZipPostalCodeDbEntities object using the connection string found in the 'ZipPostalCodeDbEntities' section of the application configuration file.
        /// </summary>
        public ZipPostalCodeDbEntities() : base("name=ZipPostalCodeDbEntities", "ZipPostalCodeDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ZipPostalCodeDbEntities object.
        /// </summary>
        public ZipPostalCodeDbEntities(string connectionString) : base(connectionString, "ZipPostalCodeDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ZipPostalCodeDbEntities object.
        /// </summary>
        public ZipPostalCodeDbEntities(EntityConnection connection) : base(connection, "ZipPostalCodeDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ZipCodeTable> ZipCodeTables
        {
            get
            {
                if ((_ZipCodeTables == null))
                {
                    _ZipCodeTables = base.CreateObjectSet<ZipCodeTable>("ZipCodeTables");
                }
                return _ZipCodeTables;
            }
        }
        private ObjectSet<ZipCodeTable> _ZipCodeTables;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ZipCodeTables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToZipCodeTables(ZipCodeTable zipCodeTable)
        {
            base.AddObject("ZipCodeTables", zipCodeTable);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ZipPostalCodeDbModel", Name="ZipCodeTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ZipCodeTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ZipCodeTable object.
        /// </summary>
        /// <param name="zipKey">Initial value of the zipKey property.</param>
        /// <param name="zipCode">Initial value of the ZipCode property.</param>
        /// <param name="city">Initial value of the City property.</param>
        /// <param name="state">Initial value of the State property.</param>
        public static ZipCodeTable CreateZipCodeTable(global::System.Int32 zipKey, global::System.String zipCode, global::System.String city, global::System.String state)
        {
            ZipCodeTable zipCodeTable = new ZipCodeTable();
            zipCodeTable.zipKey = zipKey;
            zipCodeTable.ZipCode = zipCode;
            zipCodeTable.City = city;
            zipCodeTable.State = state;
            return zipCodeTable;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 zipKey
        {
            get
            {
                return _zipKey;
            }
            set
            {
                if (_zipKey != value)
                {
                    OnzipKeyChanging(value);
                    ReportPropertyChanging("zipKey");
                    _zipKey = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("zipKey");
                    OnzipKeyChanged();
                }
            }
        }
        private global::System.Int32 _zipKey;
        partial void OnzipKeyChanging(global::System.Int32 value);
        partial void OnzipKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ZipCode
        {
            get
            {
                return _ZipCode;
            }
            set
            {
                OnZipCodeChanging(value);
                ReportPropertyChanging("ZipCode");
                _ZipCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ZipCode");
                OnZipCodeChanged();
            }
        }
        private global::System.String _ZipCode;
        partial void OnZipCodeChanging(global::System.String value);
        partial void OnZipCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();

        #endregion
    
    }

    #endregion
    
}
